apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
    - name: agent
      port: 50000
      targetPort: 50000
      nodePort: {{ .Values.service.agentPort }}